### PR TITLE
Use tabs instead of spaces

### PR DESCRIPTION
**Pull request by rossellhayes**
- Set `.Rproj` option to use tabs instead of spaces.
- Use [`grkstyle::grk_reindent_tabs_pkg()`](https://github.com/gadenbuie/grkstyle) to convert indenting spaces to tabs.
- Remove multiple spaces used for alignment, e.g.
```r
.result   <- "1"
.solution <- 1
```

### CODE REVIEW

**Comment by rossellhayes** [comment]
We'll have to wait for the automated package maintenance to be updated, since right now it converts all the tabs back to spaces

**Comment by gadenbuie** [comment]
I'm going to merge this and see if it works 🤞

**Comment by rossellhayes** [comment]
@gadenbuie Unfortunately auto-pkg-maintenance turned all the tabs back into spaces in [49beb02](https://github.com/rstudio/tblcheck/pull/114/commits/49beb029bc3c4c4557c1b55b905ea30951a7e461). It looks like this PR is still using spaces.

**Comment by gadenbuie** [comment]
Yeah but if it works correctly, the project setting from https://github.com/rstudio/tblcheck/pull/114/commits/7f66af64beeece8483d063bdc9a1ae6c14adbace will win

**Comment by gadenbuie** [comment]
ooh looks like it worked! https://github.com/rstudio/tblcheck/pull/125/files

**Comment by rossellhayes** [comment]
Oh I see now! The tabs changed in the other PR

**Pull request merged**
